name: analytics
description: A Flutter package which adds analytics support

environment:
  sdk: ^3.8.1
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
