name: camera_platform_interface
description: A common platform interface for the camera plugin.
version: 0.0.1

environment:
  sdk: ^3.8.1
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  very_good_analysis: ^9.0.0
