name: authentication_repository
description: Repository which manages user authentication using Firebase Authentication.
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=2.0.0"

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0