name: image_compositor
description: A Flutter package which adds image compositing support via web workers

environment:
  sdk: ^3.8.1
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  test: ^1.21.7
  very_good_analysis: ^9.0.0
