name: photobooth_ui
description: UI Toolkit for the Photobooth Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=2.0.0"

dependencies:
  equatable: ^2.0.7
  flame: ^1.30.1
  flutter:
    sdk: flutter
  platform_helper:
    path: ../platform_helper
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.3.2
  very_good_analysis: ^9.0.0

flutter:
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
