name: camera_web
description: Web platform implementation of camera
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">2.0.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CameraPlugin
        fileName: camera_web.dart

dependencies:
  camera_platform_interface:
    path: ../camera_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  test: ^1.21.7
  very_good_analysis: ^9.0.0
